### ISSUE TITLE
Implement rule for checking all projects have a client

### ISSUE THREAD

**Issue by buep** [Praqma/toggl-rules#12]

**Comment by edipetres** [comment]
@buep This seems to be the shortest rule to code among the proposed ones. The API gives me a list of projects in a workspace with these details:

```js
{
		"id":909,
		"wid":777,
		"cid":987,
		"name":"Very lucrative project",
		"billable":false,
		"is_private":true,
		"active":true,
		"at":"2013-03-06T09:15:18+00:00"
}
```

It doesn't have any person id attached to a project, but we could have someone (Leif?) notified when one misses a client.

**Comment by buep** [comment]
When the project isn't attached to a client, the project owner (or creater) should be notified.

**Comment by edipetres** [comment]
The API, unfortunately, doesn't provide me with any reference to a person. See above. An extended response is still insufficient:

```js
{
  "id": 84958719,
  "wid": 1604223,
  "cid": 32687922,
  "name": "Consulting",
  "billable": true,
  "is_private": false,
  "active": true,
  "template": false,
  "at": "2017-11-29T07:41:25+00:00",
  "created_at": "2017-11-29T07:40:44+00:00",
   "color": "5",
   "auto_estimates": false,
   "actual_hours": 10,
   "hex_color": "#4bc800"
}
```

**Comment by buep** [comment]
but you closed it? does it mean it is solved?

**Comment by buep** [comment]
Never mind I see you notify in the channel, and not specific persons... that is fine :-)

**Comment by buep** [comment]
I can't find the person in the UI either... because when the project is workspace public there is not person

**Comment by edipetres** [comment]
Yes, the main logic was done so I delivered it. We can figure out later which channel to post into.
