### ISSUE TITLE
Suggest how to do the invoice reports

### ISSUE THREAD

**Issue by buep** [Praqma/toggl-rules#13]
Don't code this before we talked design and implementation, but we would like an invoice report with some of the features or things like this:

* Create invoice line pr toggl client
* each invoice line is a project
* Projects with the name `Account management` is ignored.
* Tasks with the name `Travel` is taking out under the project to shown separately
* For each person logging time, we look up the price pr. person pr. customer in configuration file (in git)

How much of this is easy to find in Toggl

**Comment by edipetres** [comment]
![img_2567](https://user-images.githubusercontent.com/17469252/33554788-6630ef4a-d8fe-11e7-908b-324b8b4c8e3b.JPG)

**Comment by buep** [comment]
I'm making this issue workable, let's see how far we get in one day.
