### ISSUE TITLE
Force join people before mention them

### ISSUE THREAD

**Issue by buep** [Praqma/toggl-rules#31]
Slack write in their help:

> You'll only receive notifications for channels that you're a member of. If you're mentioned in a channel that you haven't joined, the sender can choose whether or not to send you a notification.

So when people leave the notification channel they will no see if we mention them.

Thus they should be added to the channel if not there. 
Then it doesn't matter people leave, and those that do the right thing will never be bothered with the channel again.

**Comment by RandomSort** [comment]
@MadsBaggesen mentioned that if we have this information we could DM people rather than putting information in a challenge.

**Comment by buep** [comment]
@edipetres we would like this feature also now we progressed with the other.

If people are not part of the channel, then join them, before mentioning them. Then they can leave again after they have seen the notification.

**Comment by buep** [comment]
Is it deployed @edipetres ? Looking forward to it working tomorrow :-)

**Comment by buep** [comment]
oh, never mind... I see #65
