### ISSUE TITLE
All time entries in certain projects (praqma to start with) needs a comment

### ISSUE THREAD

**Issue by buep** [Praqma/toggl-rules#32]
So no matter if they are on task or project level, a comment might be required.

That requirement of a comment to a time entry, can come from either a client, a project or tasks.

For example: 

* For client1 all time entries must have a comment.
* For projectx all time entries must have a comment
* For tasksy all time entries must have a comment

**Comment by RandomSort** [comment]
For me as account manager at a client - this does not give me any value at my current clients.
We still log a lot of time on praqma-common and this would be a tremendous help in getting information about what is happening there so :+1: for that :)

**Comment by buep** [comment]
Moved to backlog, we will implement this feature in next iteration.

**Comment by buep** [comment]
@edipetres this feature you can maybe look at. 

We need a configuration file to contain the list of clients, or projects that have this requirement of all time entries having a comment.

Don't roll it out before Leif announces it.

**Comment by edipetres** [comment]
Will have to decide if we want to use a white or a blacklist? Depending on whether we have a few projects that don't require comments, or we have a few that do need comments.

**Comment by buep** [comment]
I think we will use a "include" list, as it will only be a handful of projects that will have this requirement.
