### ISSUE TITLE
Check time entries for the current month

### ISSUE THREAD

**Issue by edipetres** [Praqma/toggl-rules#38]

**Comment by buep** [comment]
This is done... will close. Please create a new issues on creating the /checkup command later.

**Comment by edipetres** [comment]
The reminder today was manually triggered, we still need to implement the checks for the month in the code.

**Comment by buep** [comment]
We don't need the checks automated... if was just Leif who wanted a November check this one-time.

Going forward we will do these checks with our bot, see #11 .... so we continue with just the two daily checks.

**Comment by edipetres** [comment]
Alright, that task then goes to #11 👍
