### ISSUE TITLE
Evening reminder shouldn’t post about correct time entries

### ISSUE THREAD

**Issue by edipetres** [Praqma/toggl-rules#39]

**Comment by buep** [comment]
Not sure exactly what you mean, but actually I like the bot telling everything is fine. Like a clap on the shoulders to us.

But you might be right we don't want the evening reminder to report back saying all good, but the morning reminder should definitely do it :-)

**Comment by edipetres** [comment]
Yes, that's right. What I jotted down was that we don't want two separate everything is ok messages. Say, if we're told in the morning time entries are correct then we don't want a second post in the evening.

**Comment by mortench3000** [comment]
How about using another channel for the shoulder clapping, and eliminate the empty posts from the main channel?

**Comment by buep** [comment]
Then I would rather skip it... beside the shoulder clapping it have the purpose of letting us know the check is running. But that could also be left to a monitoring system.

**Comment by buep** [comment]
Decision with Leif - we will not post if nothing is wrong. So silence if all check parses.

**Comment by edipetres** [comment]
Then I will make an issue to turn ok messages off. I presume you want it turned off for both reminders :)

**Comment by buep** [comment]
Yes do that... then we close this one. Reference this issue so they get linked.
