### ISSUE TITLE
Finish up delivering the invoice dataset

### ISSUE THREAD

**Issue by edipetres** [Praqma/toggl-rules#58]
A number of issues have been completed for the invoices project. A couple of more decisions left, so I'm listening to your feedback @buep on those:
- [x] generate the CSV file with invoices
- [x] send an email with an attachment
- [x] get a special Praqma email account to send invoices from (needs to have 2FA on to request an app-specific password)
- [x] how to trigger the program (by Slack? - currently can give an URL that will trigger the sending of the email)

**Comment by buep** [comment]
See #48 regarding our feedback on the last demo we did.

The program should be triggered by a bot command as we agreed last time.

Sending the mail should be done with the same setup we use in our Jenkins servers., using the Google account we have for it.
See this file on how we send mails from our CI servers: https://github.com/Praqma/praqma-jenkins/blob/master/dockerizeit/master/jenkins.properties#L113
Can you use that, if I can give you the password?

**Comment by edipetres** [comment]
I should be able to use it. However, there were some extra quirks due to Google's high security. 
So let's see if I can get it working with a password.

**Comment by edipetres** [comment]
completed in #61
