### ISSUE TITLE
Slack command throws error

### ISSUE THREAD

**Issue by edipetres** [Praqma/toggl-rules#60]
Receives this error when running the command `/invoices` on our slack app:
```
Darn - that slash command didn't work (error message: `400_client_error`).
```

**Comment by edipetres** [comment]
Have been looking deeply into the issue, but could not get a solution working.
Verified oauth access, validity of tokens and passwords, went through a new fresh slack app installation but could not get the commands working on that one either. Debugging is made hard as logs are limited and I cannot figure out why Slack does not connect to the url endpoint its assigned while I can manually trigger it. Tried even a proxy server to see the outgoing request from the Slack app but the content is encoded so cannot debug from slack's side. I suspect a bug with stdlib's slack app template or the service.

So currently we cannot use slack commands with stdlib. Other alternatives are AWS's Lambda that has a bit more complex slack command setup, but seems to give more control and overview. Could try that one. Looking for your feedback @buep

**Comment by buep** [comment]
Yes, and we didn't manage to solve it together. For now we have a workaround proposed in #62 and will continue the work there.
