### ISSUE TITLE
The invoice generation call in toggl-rules are open to public internet

### ISSUE THREAD

**Issue by buep** [Praqma/toggl-rules#62]
@edipetres and I could get oauth to work when implementing slack commands, see #59 and #60 so we made a public wide internal open lib call that will generate invoice lines (#61).

This is not very secure, but outsider Praqma's organization can't access our invoice data as the email-address is hard-coded in the code thus so the only risk it imposes is that someone can call the method and spam edmon and Smadar with invoice emails.

**Comment by buep** [comment]
@les-praqma this was closed after a few hours by @edipetres again in #63 with commit https://github.com/Praqma/toggl-rules/commit/a932b4e9d8c3022ad97cd70ede15ac26331bead9

So no harm done ;-)

But we still couldn't get the OAuth to work between Slack and our toggl-rule deployment on stdlib, and it will not be easy to debug.

So I suggest we for now just make an google mail alias called invoicelines@praqma.net and add you, Smadar, Edmon and I so when someone writes `/invoices` in slack we receive the invoice lines.

Would that be an okay solution for now?

Then we add getting the OAuth to work on the backlog.

**Comment by edipetres** [comment]
closed in #73
