### ISSUE TITLE
Fix missing comments reminder and deploy new version

### ISSUE THREAD

**Issue by edipetres** [Praqma/toggl-rules#66]
The new version that checks for missing time entry descriptions #32 has to be finished up and deployed (waiting for Leif)
- [x] post to Slack channel
- [x] implement include projects configuration
- [x] make it run only on weekdays
- [x] add token based authentication
- [x] describe authentication in readme
- [x] deploy new version and schedule it on StdLib

**Comment by buep** [comment]
not filtering out... filtering in... we would like an include statement on which projects to include.

For now this is only praqma:common.
