### ISSUE TITLE
Finish up invoice lines and evaluate and validate hours with Leif and Smadar

### ISSUE THREAD

**Issue by buep** [Praqma/toggl-rules#69]
- [x] Ask @lakruzz to make an invoicelines@praqma.net alias, that will send messages to Leif, Smadar, Edmond and Bue (praqma mails), Mike, Adam

- [x] update the receiver email to be invoicelines@praqma.net when calling the invoice function.

- [x] Update the email to contain information about how the mail was produced, e.g. "This mail was generated because the /invoiceline commands was called in toggl-rules channel and you recieve this mail because you're on the mail-alias invoicelines@praqma.net"

- [x] Present and evaluate the last invoice lines from December with Leif and Smadar, and have them check they are correct and useful so they can be used for invoices in February.
 
Any feedback you will write in a new issues, that we can later decide to fix and improve and groom.

**Comment by buep** [comment]
I asked Lars to create the alias.

**Comment by buep** [comment]
The alias is working now if you received my mail. I don't get it myself.

**Comment by edipetres** [comment]
I started receiving emails this morning from the alias account

**Comment by edipetres** [comment]
finished in #77
