### ISSUE TITLE
Possible bug - users wasn't warned about logging time without project

### ISSUE THREAD

**Issue by buep** [Praqma/toggl-rules#70]
jasmine:

>  I have a question @bue.petersen. I can see that Mariusz registered some time last week without any project. I have not seen a message in toggl fix channel. How does it work?

**Comment by buep** [comment]
@edipetres can you spend a short time investigating is this might be a bug?

**Comment by JasmineCrozier** [comment]
The entries without project are here: https://toggl.com/app/reports/detailed/1604223/from/2018-01-01/to/2018-01-15/users/3814408/projects/0/billable/both

**Comment by JasmineCrozier** [comment]
@buep @edipetres one thing could be that I did not add Mariusz correctly to toggl
It was the first time that I added anyone...

**Comment by edipetres** [comment]
@JasmineCrozier Thanks for finding this bug, Jasmine. It should be fixed now :)

**Comment by JasmineCrozier** [comment]
@edipetres cool, thanks. Let's see if it finds the entries before tomorrow morning.
