### ISSUE TITLE
Description reminder to show relevant <client>:<project> in message

### ISSUE THREAD

**Issue by edipetres** [Praqma/toggl-rules#74]
Add it in version 0.5.1

**Comment by buep** [comment]
from slack


----

15:47] 
Toggl-Bot APP Dear colleagues, I've noticed some of you is missing a description in your projects registered yesterday:
 • @eddie in Praqma:Common


[15:47] 
eddie joined #toggl-bot-testing by invitation from Bot User.


[15:51] 
bue.petersen fine adding the projct to the person... in case we add more in the configuration file
----

looks good
